### PR TITLE
Use Gradle's version catalog for embulk-util-text and embulk-util-timestamp

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Comment by dmikurube** [comment]
Thanks!

**Comment by hiroyuki-sato** [comment]
> It's okay this time, but let me leave a recommendation for next time -- when upgrading a dependency library, it'd be nice to have gradle.lockfile at first before upgrade, and then do the upgrade. By this order, we can confirm which library is upgraded explicitly.

Does this mean the following?

1. create `gradle.lockfile` using `./gradlew dependencies --write-locks` when the file doesn't exist.
2. Use Gradle's version catalog(create the `gradle/libs.versions.toml` file.)
3. Update dependency library version.
4. Update `gradle.lockfile` using `./gradlew dependencies --write-locks`

**Comment by dmikurube** [comment]
I meant :

Prioritize this at first, then make it a pull request without other changes, so that we can confirm "the current status".
> 1. create `gradle.lockfile` using `./gradlew dependencies --write-locks` when the file doesn't exist.

After that, do anything in any order. We (incl. reviewers) can confirm what is going to change.

Otherwise, without `gradle.lockfile`, reviewers cannot be aware even if any silent dependency change is happening. That's the concern.

**Comment by hiroyuki-sato** [comment]
I got it. Thanks!

**Comment by hiroyuki-sato** [comment]
Sorry, I posted my question to another repository.

**Pull request merged**
