### PR TITLE
Upgrade embulk-util-config to 0.3.4, embulk-util-file to 0.1.5, and embulk-util-text to 0.1.3

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Comment by dmikurube** [comment]
It fails as of now, but it should be okay when embulk-util-text:0.1.3 is ready.

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
